apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: persistentvolumesyncs.storage.cndev.nl
spec:
  group: storage.cndev.nl
  scope: Cluster
  names:
    plural: persistentvolumesyncs
    singular: persistentvolumesync
    kind: PersistentVolumeSync
    shortNames: [pvsync]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - protectedCluster
                - cloudProvider
                - mode
                - retention
              properties:
                clusterNameKey:
                  type: string
                cloudProvider:
                  type: string
                mode:
                  type: string
                  enum:
                    - Protected
                    - Recovery
                retention:
                  type: integer
            status:
              type: object
              properties:
                succeeded:
                  type: boolean
      subresources:
        status: {}
